#! /usr/bin/env ruby

# ******************************
# GIT 2 SVN Tester Script
# ******************************
# == Synopsis 
#
# == Examples
#
#
# == Usage 
# (1) ./git2svn <path to git dir or file> <svn repo address> [--file=name] [--ignore=ignore list comma seperated] [--config=name] [--message="svn message"]
#     Examples: 
#       => ./git2svn ~/gitrepos/myrepo/ http://my.svn.repo/directory/
#       => ./git2svn ~/gitrepos/myrepo/ http://my.svn.repo/directory/ --message="my message" --ignore==.svn,.git,public,log
#       => ./git2svn ~/gitrepos/myrepo/myfile http://my.svn.repo/directory/ --file=myfile --message="my message" --ignore==.svn,.git,public,log
#       => ./git2svn ~/gitrepos/myrepo/myfile http://my.svn.repo/directory/ --file=myfile --message="my message" --ignore==.svn,.git,public,log --save=standard
# (2) ./git2svn --use=<name> [--message="svn message"]
#
# == Author
# Evin Grano, Mike Ball
#
# == Copyright
#   Copyright (c) 2008-2011 Evin Grano, Mike Ball. All Rights Rserved.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require './lib'
puts "START TEST 1: Basic Directory => GOOD: <svn_repo> <git_path> ./git2svn ~/gitrepos/myrepo/ http://my.svn.repo/directory/"
app = Git2Svn.new(['./test_dir/', 'https://subversion/svn/my/repo/branches/version2/myDir/'],STDIN)
puts "END TEST 1\n"

puts "START TEST 2: Basic file => GOOD: <svn_repo> <git_path> ./git2svn ~/gitrepos/myrepo/ http://my.svn.repo/directory/ --file=test_file.txt"
app = Git2Svn.new(['./test_dir/test_file.txt', 'https://subversion/svn/my/repo/branches/version2/myDir/', '--file=test_file.txt'],STDIN)
puts "END TEST 2\n"
# app.run
